
class RPVocab:
    """
    Contains all the keys present in the json data
    """
    abstract = 'abstract'
    affiliation = 'affiliation'
    authors = 'authors'
    back_matter = 'back_matter'
    bib_entries = 'bib_entries'
    body_text = 'body_text'
    cite_spans = 'cite_spans'
    country = 'country'
    doi = 'DOI'
    email = 'email'
    end = 'end'
    first = 'first'
    institution = 'institution'
    issn = 'issn'
    laboratory = 'laboratory'
    last = 'last'
    latex = 'latex'
    location = 'location'
    metadata = 'metadata'
    middle = 'middle'
    other_ids = 'other_ids'
    pages = 'pages'
    paper_id = 'paper_id'
    postcode = 'postCode'
    ref_entries = 'ref_entries'
    ref_id = 'ref_id'
    ref_spans = 'ref_spans'
    section = 'section'
    settlement = 'settlement'
    start = 'start'
    suffix = 'suffix'
    text = 'text'
    title = 'title'
    type = 'type'
    venue = 'venue'
    volume = 'volume'
    year = 'year'
    # added for inverted index
    full_text = 'full_text'
    headers = 'headers'
